import React from 'react';
export const metadata = {
  title: "History info| KeenKeeper",
  description: "Generated by create next app",
};


const TimeLimePage = () => {
    return (
        <div>
            <h1 className='text-sky-500 bg-white text-9xl text-center'>timeline page</h1>
        </div>
    );
};

export default TimeLimePage;