import React from 'react';
export const metadata = {
  title: "Analetcis info| KeenKeeper",
  description: "Generated by create next app",
};


const StartsPage = () => {
    return (
        <div>
            <h1 className='text-sky-500 bg-white text-9xl text-center'>stats page</h1>
        </div>
    );
};

export default StartsPage;