import React from 'react';
export const metadata = {
  title: " Friend info| KeenKeeper",
  description: "Generated by create next app",
};


const FriendDetailPage = () => {
    return (
        <div>
          <h1 className='text-sky-500 bg-white text-9xl text-center'>friend detail page</h1>  
        </div>
    );
};

export default FriendDetailPage;