import React from 'react';
import { IoAddCircleOutline } from "react-icons/io5";


export const metadata = {
  title: "All Friends| KeenKeeper",
  description: "Generated by create next app",
};


const  DashBoardPage = () => {
    return (
        <div>
            <div className='mx-auto mt-30 content-center items-center text-center'>
                <h1 className='text-black bg-white text-4xl text-center font-bold'>Friends to keep close in your life</h1>
            <p className='text-center  text-gray-500 '>Your personal shelf of meaningful connections. <br /> Browse, tend, and nurture the
relationships that matter most.</p>
<button className='btn text-white bg-green-900 mx-auto content-center items-center'><IoAddCircleOutline />
Add Friend
</button>
            </div>

            <div className='flex gap-10 p-10 mx-auto my-20 justify-center'>
                
                <div className='rounded-md bg-emerald-50 text-center text-black shadow-2xl p-8 '>
                    <h2>10</h2>
                    <p className='text-gray-500'>Total friends</p>
                </div>
                <div className='rounded-md bg-emerald-50 text-center text-black shadow-2xl p-8 '>
                    <h2>10</h2>
                    <p className='text-gray-500'>On Track</p>
                </div>
                <div className='rounded-md bg-emerald-50 text-center text-black shadow-2xl p-8 '>
                    <h2>10</h2>
                    <p className='text-gray-500'>Need Attention</p>
                </div>
                <div className='rounded-md bg-emerald-50 text-center text-black shadow-2xl p-8 '>
                    <h2>10</h2>
                    <p className='text-gray-500'>Interactions This Month</p>
                </div>
            </div>
        </div>
    );
};

export default  DashBoardPage;