import React from 'react';
export const metadata = {
  title: "All Friends| KeenKeeper",
  description: "Generated by create next app",
};


const  DashBoardPage = () => {
    return (
        <div>
            <h1 className='text-sky-500 bg-white text-9xl text-center'>Dashboard page</h1>
        </div>
    );
};

export default  DashBoardPage;